#!/bin/bash

INSTALL_PATH=${INSTALL_PATH:-${HOME}/bin/vagrant}
SRC_ROOT=$(cd $(dirname $0)/.. && pwd)

cd "${SRC_ROOT}"

mkdir -p $(dirname "${INSTALL_PATH}")
cp -i bin/vagrant "${INSTALL_PATH}"
echo "Install Vagrant wrapper to ${INSTALL_PATH}"
